CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(100),
    CONTRASENA VARCHAR(255)
);

CREATE TABLE VEHICULOS (
    ID_VEHICULO INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(100),
    MODELO VARCHAR(100),
    AÑO INT,
    PRECIO DECIMAL(10, 2),
    DESCRIPCION VARCHAR(300),
    ESTADO VARCHAR(50),
    VENDEDOR VARCHAR(100),
    TELEFONO_VENDEDOR BIGINT
);

CREATE TABLE COMPRAS (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    FECHA_COMPRA DATE,
    ID_VEHICULO INT,
    TOTAL DECIMAL(10, 2),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO)
);

--CONTREASEÑAS 123456
INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASENA) 
VALUES ('Juan Pérez', 'juan.perez@example.com', '$2y$10$d6POOPxvzXHrTHBT./UyAe.bZFH90l1ZWDpfZZ7i7mCZEY5DejzNq');
INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASENA) 
VALUES ('María López', 'maria.lopez@example.com', '$2y$10$d6POOPxvzXHrTHBT./UyAe.bZFH90l1ZWDpfZZ7i7mCZEY5DejzNq');
INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASENA) 
VALUES ('Carlos García', 'carlos.garcia@example.com', '$2y$10$d6POOPxvzXHrTHBT./UyAe.bZFH90l1ZWDpfZZ7i7mCZEY5DejzNq');

INSERT INTO VEHICULOS (MARCA, MODELO, AÑO, PRECIO, DESCRIPCION, ESTADO, VENDEDOR, TELEFONO_VENDEDOR)
VALUES ('Toyota', 'Corolla', 2020, 10800000.00, 'Auto en excelente estado, único dueño', 'Usado', 'AutoShop', 1234567890);
INSERT INTO VEHICULOS (MARCA, MODELO, AÑO, PRECIO, DESCRIPCION, ESTADO, VENDEDOR, TELEFONO_VENDEDOR)
VALUES ('Honda', 'Civic', 2021, 13200000.00, 'Auto nuevo, recién salido del concesionario', 'Nuevo', 'CarDealer', 9876543210);
INSERT INTO VEHICULOS (MARCA, MODELO, AÑO, PRECIO, DESCRIPCION, ESTADO, VENDEDOR, TELEFONO_VENDEDOR)
VALUES ('Ford', 'Mustang', 2018, 15000000.00, 'Auto deportivo, bien mantenido', 'Usado', 'SpeedMotors', 1230984567);

INSERT INTO COMPRAS (ID_USUARIO, FECHA_COMPRA, ID_VEHICULO, TOTAL)
VALUES (1, '2023-01-15', 1, 10800000.00);
INSERT INTO COMPRAS (ID_USUARIO, FECHA_COMPRA, ID_VEHICULO, TOTAL)
VALUES (2, '2023-05-22', 2, 13200000.00);
INSERT INTO COMPRAS (ID_USUARIO, FECHA_COMPRA, ID_VEHICULO, TOTAL)
VALUES (3, '2023-08-10', 3, 15000000.00);


